apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  db_name: {{ .Values.db.name | b64enc | quote  }}
  db_user: {{ .Values.db.user | b64enc | quote  }}
  db_pass: {{ .Values.db.pass | b64enc | quote  }}
  db_host: {{ .Values.db.host | b64enc | quote  }}
  db_driver: {{ .Values.db.driver | b64enc | quote  }}
  db_port: {{ .Values.db.port | b64enc | quote  }}
  aws_access_key_id: {{ .Values.aws.access_key_id | b64enc | quote  }}
  aws_secret_access_key: {{ .Values.aws.secret_access_key | b64enc | quote  }}
  slack_webhook: {{ .Values.slack.webhook | b64enc | quote  }}
